# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('poids', models.FloatField(default=0)),
                ('nbr_box', models.IntegerField(default=0)),
                ('client', models.CharField(max_length=200)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Produit')),
            ],
        ),
    ]
