# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_client'),
        ('polls', '0002_operation'),
    ]

    operations = [
    ]
