# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20171214_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.FloatField(default=0)),
                ('nbr_cartons', models.IntegerField(default=0)),
                ('date', models.DateField(verbose_name="Date de l'opération")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Produit')),
            ],
        ),
    ]
