# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='produit',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
